### ISSUE TITLE
Add Function to customise the list of resources 

### ISSUE THREAD

**Issue by ismail9875** [fairbird/KeyAdder#22]
I thing is more efficiene Add a option to agregate a new source of SoftCam.key,
For Example in the last version 7.4 the plugin have six resources, the idea is add a button for include more resources.

**Comment by fairbird** [comment]
We can not do that method to add new button to add new sources by manually !!!
Why ?! Because not all source sites can do same job for download SoftCam.key. Some site need some special codes, some need more function codes to download files.
